# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "categories.html"]

permalink: /:title
pygments: true
markdown: rdiscount

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : 夜惊心的博客
tagline: Site Tagline
author :
  name : 夜惊心
  email : yjx27@qq.com
  github : yejinxin
  twitter : yejinxin
  feedburner : yejinxin

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
url : http://yejinxin.github.io